name: "Deploy Report to GitHub Pages"
description: "Uploads a report to GitHub Pages and updates index.html"
inputs:
  report_path:
    description: "Path to the report to be copied"
    required: true
  report_name:
    description: "Name of the report directory"
    required: true
  report_file:
    description: "Name of the report file to be used as the report link in Github Pages."
    required: false
    default: "index.html"

runs:
  using: "composite"
  steps:
    - name: Download Existing Reports
      uses: actions/download-artifact@v4
      with:
        path: reports
        pattern: github-pages-*
        merge-multiple: true

    - name: Copy New Report
      shell: bash
      run: |
        mkdir -p reports/${{ inputs.report_name }}
        cp -R ${{ inputs.report_path }}/. reports/${{ inputs.report_name }}
        
        # Rename specified report file to index.html
        if [[ -f "reports/${{ inputs.report_name }}/${{ inputs.report_file }}" && "${{ inputs.report_file }}" != "index.html" ]]; then
          mv "reports/${{ inputs.report_name }}/${{ inputs.report_file }}" "reports/${{ inputs.report_name }}/index.html"
        fi

    - name: Regenerate Index.html
      shell: bash
      run: |
        echo "<!DOCTYPE html>" > reports/index.html
        echo "<html><head><title>Test Reports</title>" >> reports/index.html
        echo "<style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f4f4f4; }
        </style></head><body>" >> reports/index.html
        echo "<h1>Test Reports</h1>" >> reports/index.html
        echo "<table><tr><th>Report</th><th>Last Updated</th></tr>" >> reports/index.html
        
        for d in reports/*/; do
        dir=$(basename "$d")
        timestamp=$(stat -c %y "$d" | cut -d' ' -f1) # last modified date
        echo "<tr><td><a href='$dir/index.html'>$dir Report</a></td><td>$timestamp</td></tr>" >> reports/index.html
        done
        echo "</table></body></html>" >> reports/index.html

    - name: Upload Updated Reports to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages-${{ inputs.report_name }}
        path: 'reports/'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages-${{ inputs.report_name }}