name: Dependabot Auto-Merge & Security

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:  # Allows manual triggering

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable Auto-Merge for Dependabot PRs
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}