name: Build & Test

on:
  push:
    tags:
      - 'v*'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml


  test:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Deploy Test Report
        if: always()
        uses: ./.github/actions/deploy-report
        with:
          report_path: target/site/allure-maven-plugin
          report_name: tests

      - name: Deploy Coverage Report
        if: always()
        uses: ./.github/actions/deploy-report
        with:
          report_path: target/site/jacoco/
          report_name: coverage

  release:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: chess-${{ github.ref_name }}.jar
          path: target/*.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          files: target/chess-${{ github.ref_name }}.jar
          body: "New release of the application."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}