name: Security Scan

on:
  workflow_run:
    workflows: [ "Build & Test" ]
    types:
      - completed
  schedule:
    - cron: "0 4 * * 1,4"


jobs:
  security-scan:
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
      || github.event_name == 'schedule'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache OWASP Dependency Check Data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: owasp-db-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            owasp-db-${{ runner.os }}-


      - name: OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY }}

      - name: Get Latest Version
        id: version
        uses: ./.github/actions/get-version

      - name: Upload Security Reports
        uses: ./.github/workflows/upload-report.yml
        with:
          report_name: "security"
          source_dir: "target/dependency-check-report"
          version: "${{ env.VERSION }}"