name: Upload Reports
on:
  workflow_call:
    inputs:
      report_name:
        required: true
        type: string
      source_dir:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Ensure Directories Exist
        run: |
          mkdir -p reports/latest/${{ inputs.report_name }}
          mkdir -p reports/${{ inputs.version }}/${{ inputs.report_name }}

      - name: Copy Report Files
        run: |
          cp -r ${{ inputs.source_dir }}/* reports/latest/${{ inputs.report_name }}/
          cp -r ${{ inputs.source_dir }}/* reports/${{ inputs.version }}/${{ inputs.report_name }}/

      - name: Commit and Push Reports
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd reports
          git add .
          git commit -m "Update ${{ inputs.report_name }} reports for ${{ inputs.version }}"
          git push