name: Versioning & Tagging

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all tags are available
          # Token used for workflows to tag and bump versions, so that they can trigger further workflows from a tagging action.
          # See https://stackoverflow.com/questions/75348291/how-to-trigger-github-actions-workflow-whenever-a-new-tag-was-pushed
          token: ${{ secrets.VERSIONING_TOKEN }}
      - name: Get Latest Version
        id: version
        run: echo "VERSION=$(git describe --tags --abbrev=0 || echo '0.0.0')" >> $GITHUB_ENV

      - name: Get next version # checks if conventional commit would cause a new version
        id: get_next_version
        uses: thenativeweb/get-next-version@main
        with:
          prefix: 'v'

      - name: Update pom.xml Version
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          mvn versions:set -DnewVersion=${{steps.get_next_version.outputs.version}} -DgenerateBackupPoms=false

      - name: Commit Updated Version Files
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pom.xml
          git commit -m "chore: bump version to ${{steps.get_next_version.outputs.version}}" || exit 0
          git push origin main

      - name: Create New Tag
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          git tag -a ${{steps.get_next_version.outputs.version}} -m "Version ${{steps.get_next_version.outputs.version}}"
          git push origin ${{steps.get_next_version.outputs.version}}